name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i -D
    - name: Run ESLint
      run: npx run eslint . --ext .js,.jsx,.ts,.tsx
